# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: '安装 Node.js'

- script: |
    npm install
    npm run build
  displayName: '安装依赖以及进行构建'

- script: gulp                       # include any additional options that are needed
  displayName: '运行gulp'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-RESULTS.xml'
    testRunTitle: 'Test results for JavaScript using gulp'
  displayName: '发布测试报告'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
  displayName: '发布代码覆盖率报告'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)'
#   displayName: '发布文件到Azure Pipelines'
  
# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(System.DefaultWorkingDirectory)'
#     Contents: |
#       **\*.js
#       package.json
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
#   displayName: '从工作目录复制必要的文件到暂存目录'

# - task: PublishBuildArtifacts@1
#   displayName: '发布artifact'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
  displayName: '为部署web App做准备'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: '发布zip'